### ISSUE TITLE
这样要怎么使用的？提示Uncaught Error: Class 'hash' not found

### ISSUE THREAD

**Issue by 2494911084** [yzh52521/webman-hash#1]
![image](https://user-images.githubusercontent.com/29133710/184073096-37eac163-5d5f-41a2-99f9-33471f280f32.png)

**Comment by yuanzhihai** [comment]
Hash::make('password'); 
就这样使用啊

**Comment by 2494911084** [comment]
> Hash::make('password'); 就这样使用啊

我安装之后，是在seed迁移文件里使用的，显示这个报错

**Comment by yuanzhihai** [comment]
找不到类 

命名空间

**Comment by 2494911084** [comment]
> 找不到类
> 
> 命名空间

需要use 吗？
