### ISSUE TITLE
注册时使用加密，那登陆时怎么对加密密码进行校验呢？

### ISSUE THREAD

**Issue by 2494911084** [yzh52521/webman-hash#3]
注册时使用加密，那登陆时怎么对加密密码进行校验呢？

**Comment by yuanzhihai** [comment]
文档里有啊
if (Hash::check('plain-text', $hashedPassword)) {
    // 密码匹配...
}

**Comment by 2494911084** [comment]
> 

哦哦 看到你贴的文档连接了
